written for https://stackoverflow.com/q/49930830/425458

In [15]:
import numpy as np

# question asker's code
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [3,2,1]
])

# doesn't work the way that op wants.
# numpy builds ixs by iterating over rows, then doing an element-wise comparison between the contents of each row and the LHS
ixs = arr != [1,2,3]
arrSliced = arr[ixs]

print('ixs:\n%s' % ixs.__repr__())
print('arrSliced:\n%s' % arrSliced.__repr__())

ixs:
array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])
arrSliced:
array([4, 5, 6, 7, 8, 9, 3, 1])


In [29]:
import numpy as np

def selectRow(arr, badrow):
    badset = set(badrow)
    return np.array([row for row in arr if badset == set(row)])
    
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [3,2,1]
])

selectRow(arr, [1,2,3])

array([[1, 2, 3],
       [3, 2, 1]])

In [38]:
print((arr != [1,2,3]).all(1))
arr[~(arr != [1,2,3]).all(1)]

[False  True  True False]


array([[1, 2, 3],
       [3, 2, 1]])

In [39]:
print((arr == [1,2,3]).any(1))
arr[(arr == [1,2,3]).any(1)]

[ True False False  True]


array([[1, 2, 3],
       [3, 2, 1]])

In [40]:
%%timeit
selectRow(arr, [1,2,3])

7.28 µs ± 85.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [34]:
%%timeit
arr[~(arr != [1,2,3]).all(1)]

8.05 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [41]:
%%timeit
arr[(arr == [1,2,3]).any(1)]

7.32 µs ± 95.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
import numpy as np

def withoutRow(arr, badrow, ordered=True):
    if ordered:
        return np.array([row for row in arr if not np.array_equal(row, badrow)])
    else:
        badset = set(badrow)
        return np.array([row for row in arr if badset != set(row)])
    
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [3,2,1]
])

# removing all exactly matching points
wr = withoutRow(arr, [1,2,3])

# removing all points with matching coordinates, any order
wrAnyOrder = withoutRow(arr, [1,2,3], ordered=False)

print(wr)
print()
print(wrAnyOrder)

[[4 5 6]
 [7 8 9]
 [3 2 1]]

[[4 5 6]
 [7 8 9]]


In [23]:
import numpy as np

def withoutRow(arr, badrow):
    return np.array([row for row in arr if not np.array_equal(row, badrow)])
    
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [3,2,1]
])

withoutRow(arr, [1,2,3])

array([[4, 5, 6],
       [7, 8, 9],
       [3, 2, 1]])

In [28]:
import numpy as np

def withoutRowUnordered(arr, badrow):
    badset = set(badrow)
    return np.array([row for row in arr if badset != set(row)])
    
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [3,2,1]
])

withoutRowUnordered(arr, [1,2,3])

array([[4, 5, 6],
       [7, 8, 9]])

In [42]:
import numpy as np
A = np.random.rand(10,5) 
A[:,-1] = np.random.randint(4, size=10)
sorted_A = A[np.argsort(A[:,4])]
splits = np.split(sorted_A, np.where(np.diff(sorted_A[:,4]))[0]+1)
idx = np.concatenate([[0], np.where(np.diff(sorted_A[:,4]))[0]+1, [A.shape[0]]])

In [45]:
np.where(np.diff(sorted_A[:,4]))[0]+1

array([4, 6, 7])

In [46]:
np.diff(idx)

array([4, 2, 1, 3])

In [47]:
idx

array([ 0,  4,  6,  7, 10])