tangent explored while writing an answer for https://stackoverflow.com/q/49888741/425458

# How to use `numpy.einsum` to do matrix or tensor operations (and possibly avoid precision errors)

Example given in terms of the operation $\mathbf{A} \cdot \mathbf{B} \cdot \mathbf{A^T} = \mathbf{C}$, where $\mathbf{A}$ is a matrix, $\mathbf{A^T}$ is it's transpose, and $\mathbf{B}$ and $\mathbf{C}$ are both symmetric matrices. It is assumed that $C_\mathbf{A} = R_\mathbf{B}$, where $R_\mathbf{x}, C_\mathbf{x}$ are the counts of rows and columns, respectively, of some matrix $\mathbf{x}$

In [80]:
import numpy as np

rowA = 3
colA = 2

shapeA = (rowA, colA)
shapeB = (colA, colA)

A = np.random.rand(*shapeA)

b = np.random.rand(*shapeB)
B = b.dot(b.T)
# check that B is symmetrical
assert np.sum(B - B.T) == 0

## multiply 3 matrices with `np.dot`

In [81]:
np.dot(np.dot(A, B), A.T)

array([[0.67529829, 0.38040981, 0.68677911],
       [0.38040981, 0.21480394, 0.38711514],
       [0.68677911, 0.38711514, 0.6985659 ]])

## various ways to multiply 3 matrices with `np.einsum`

In [83]:
np.einsum('ij,jk,lk',A,B,A)

array([[0.67529829, 0.38040981, 0.68677911],
       [0.38040981, 0.21480394, 0.38711514],
       [0.68677911, 0.38711514, 0.6985659 ]])

In [84]:
np.einsum('cd,de,fe',A,B,A)

array([[0.67529829, 0.38040981, 0.68677911],
       [0.38040981, 0.21480394, 0.38711514],
       [0.68677911, 0.38711514, 0.6985659 ]])

In [85]:
np.einsum('cd,de,ef',A,B,A.T)

array([[0.67529829, 0.38040981, 0.68677911],
       [0.38040981, 0.21480394, 0.38711514],
       [0.68677911, 0.38711514, 0.6985659 ]])

In [86]:
np.einsum(A,[0,1],B,[1,2],A,[3,2])

array([[0.67529829, 0.38040981, 0.68677911],
       [0.38040981, 0.21480394, 0.38711514],
       [0.68677911, 0.38711514, 0.6985659 ]])

# Scratch

In [45]:
import numpy as np

dim = 3
bshape = (dim,)*4
dshape = (dim,)*2

d = np.random.randint(0, 100, dshape)
D = d.dot(d.T)

In [46]:
d.dot(d.T) - d.T.dot(d)

array([[ 5218,  5234, -3826],
       [ 5234,  3924, -3744],
       [-3826, -3744, -9142]])