written for https://stackoverflow.com/q/49933144/425458

In [2]:
import numpy as np
u = np.concatenate((np.ones((3, 1)), np.zeros((3,1))), axis=1).reshape(3,1,2)
v = np.concatenate((np.zeros((3, 1)), np.ones((3,1))), axis=1).reshape(3,1,2)

In [13]:
w = u.reshape(-1,1,-1,-1) - v.reshape(1,-1,-1,-1)

ValueError: can only specify one unknown dimension

In [12]:
w.shape

(3, 3, 1, 2)

In [27]:
U = np.random.randint(0,2,size=(3,3))
V = np.random.randint(0,2, size=(3,3,4,5))

In [29]:
np.multiply.outer(U,V).shape

(3, 3, 3, 3, 4, 5)

In [26]:
print(np.einsum('ab,bcde', U, V))
print(np.einsum('ab,abcd', U, V))

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 1 0 1 0]
   [2 2 2 0 2]
   [1 1 1 0 2]
   [1 0 1 2 1]]

  [[2 2 0 2 1]
   [2 2 2 0 1]
   [0 0 0 0 1]
   [1 1 0 2 2]]

  [[1 1 1 0 0]
   [1 1 1 1 2]
   [1 1 1 2 1]
   [2 1 1 2 1]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]]
[[1 1 0 2 1]
 [2 2 2 0 1]
 [1 1 0 0 2]
 [1 0 1 2 2]]


In [34]:
U[...,None,None]*V

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 1],
         [0, 1, 1, 1, 1],
         [1, 0, 0, 0, 0],
         [1, 0, 1, 0, 0]],

        [[0, 0, 1, 1, 0],
         [0, 0, 1, 1, 1],
         [1, 0, 0, 1, 1],
         [0, 1, 1, 1, 1]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 1, 1],
         [1, 0, 1, 1, 1],
         [0, 1, 0, 1, 1],
         [0, 1, 0, 1, 1]]],


       [[[1, 1, 1, 1, 0],
         [0, 1, 0, 1, 1],
         [1, 0, 1, 1, 0],
         [1, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[1, 0, 1, 0, 1],
         [0, 0, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 0, 0, 1, 0]]]])

In [24]:
U

array([[0, 0, 0],
       [1, 1, 0],
       [0, 0, 0]])