written for [https://stackoverflow.com/q/49776310/425458](https://stackoverflow.com/q/49776310/425458)

In [22]:
    import numpy as np
    import scipy.ndimage.measurements as mnts

    A = np.array([
        [1, 0, 0, 0],
        [0, 1, 1, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0]
    ])

    B, clusters = mnts.label(A)
    
    """B is now a version of A with labeled clusters:
    
    [[1 0 0 0]
     [0 2 2 0]
     [0 2 0 0]
     [0 2 0 0]]
     
    clusters==2 holds the number of different clusters
    """
    
    sizes = mnts.sum(A, B, index=np.arange(1, clusters + 1))
    
    """sizes is a list of cluster sizes: [1, 4]
    """
    
    # now we loop over the pairs of labels and sizes
    for label,size in zip(range(1, clusters + 1), sizes):
        # assign the size to each labeled entry in B
        B[B == label] = size

    print(B)

[[1 0 0 0]
 [0 4 4 0]
 [0 4 0 0]
 [0 4 0 0]]
