written for [https://stackoverflow.com/q/49776310/425458](https://stackoverflow.com/q/49776310/425458)

In [1]:
import numpy as np
import scipy.ndimage.measurements as mnts

A = np.array([
    [1, 0, 0, 0],
    [0, 1, 1, 0],
    [0, 1, 0, 0],
    [0, 1, 0, 0]
])

# labeled is a version of A with labeled clusters:
#
# [[1 0 0 0]
#  [0 2 2 0]
#  [0 2 0 0]
#  [0 2 0 0]]
#
# clusters holds the number of different clusters: 2
labeled, clusters = mnts.label(A)

# sizes is an array of cluster sizes: [0, 1, 4]
sizes = mnts.sum(A, labeled, index=range(clusters + 1))

# mnts.sum always outputs a float array, so we'll convert sizes to int
sizes = sizes.astype(int)

# get an array with the same shape as labeled and the 
# appropriate values from sizes by indexing one array 
# with the other. See the [`numpy` indexing docs](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.indexing.html#index-arrays) for details
labeledBySize = sizes[labeled]

print(labeledBySize)

[[1 0 0 0]
 [0 4 4 0]
 [0 4 0 0]
 [0 4 0 0]]


In [2]:
import numpy as np
import scipy.ndimage.measurements as mnts

# function version
def labelBySize(arr):
    labeled, clusters = mnts.label(arr)
    sizes = mnts.sum(arr, labeled, index=range(clusters + 1)).astype(int)
    return sizes[labeled],sizes

In [3]:
arr = np.random.randint(0,2,size=(10,10))
print('Random array:\n%s' % arr)

arrLabeledBySize, arrClusterSizes = labelBySize(arr)
print('Random array cluster sizes:\n%s' % arrClusterSizes)
print('Random array labeled by cluster sizes:\n%s' % arrLabeledBySize)

Random array:
[[0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [1 0 1 0 0 1 0 0 1 1]
 [0 0 0 1 0 0 0 1 0 1]
 [0 0 1 0 0 0 0 1 1 0]
 [0 1 0 1 1 1 0 0 1 1]
 [0 1 0 1 0 0 1 1 0 1]
 [0 0 1 1 0 1 1 1 0 1]
 [1 0 0 0 1 0 1 1 0 1]
 [0 0 1 1 0 0 1 0 0 1]]
Random array cluster sizes:
[0 6 1 1 3 1 9 1 2 6 8 1 1 2]
Random array labeled by cluster sizes:
[[0 0 0 0 6 0 6 0 0 0]
 [0 0 0 0 6 6 6 0 0 0]
 [1 0 1 0 0 6 0 0 3 3]
 [0 0 0 1 0 0 0 9 0 3]
 [0 0 1 0 0 0 0 9 9 0]
 [0 2 0 6 6 6 0 0 9 9]
 [0 2 0 6 0 0 8 8 0 9]
 [0 0 6 6 0 8 8 8 0 9]
 [1 0 0 0 1 0 8 8 0 9]
 [0 0 2 2 0 0 8 0 0 9]]
